### ISSUE TITLE
make caching of JSON optional, not mandatory?

### ISSUE THREAD

**Issue by saramsey** [biolink/ontobio#301] opened 2019-03-10 22:55 UTC
I'm seeing an issue whereby if I have an OWL file ```foo.owl``` that contains an error (say a typo or something), and I load the OWL file using ```ontobio.ontol_factory.OntologyFactory().create("foo.owl")```,
the JSON resulting from the "bad" version of ```foo.owl``` will get cached in ```/tmp/ab7ae_[SOME_LONG_HEX_STRING]``` .  If I then go and correct ```foo.owl```, I still pull the bad JSON from the cache. It appears the only way to prevent this is to manually delete the file from the cache. But of course, to know which file in ```/tmp``` it is, I have to either look in the log (assuming I stored informational logging messages when I ran the above code) or I have to run ```encoded = hashlib.sha256("foo.owl".encode()).hexdigest()``` and then manually delete that file. Could we possibly have some kind of run-time switch (maybe an optional Boolean parameter to ```create```?) that could turn off this caching feature?

**Comment by saramsey** [comment] 2019-03-10 22:58
Another option is to have the JSON cache file used *only* if it is newer (in terms of file modification time) than the source file ```foo.owl```; otherwise the cache file would be deleted. That would work great as well. Basically the mandatory "opt-in" cache is making it problematic for me to clear out the junk from when I have an OWL file with some error in it. Also in general, won't the existence of the cache file prevent *any* updates to ```foo.owl``` from ever getting picked up, on subsequent runs of ```create``` ?

**Comment by saramsey** [comment] 2019-03-10 22:59
Thank you, Ontobio devs!

**Comment by deepakunni3** [comment] 2019-03-12 00:07
@saramsey Thank you for reporting this bug. 

The issue is in two parts,

#### 1. Aggressive caching by Ontobio

This can be avoided by supplying `overwrite_cache=True` to the `OntologyFactory.create()` method.
 
```py
OntologyFactory().create('hp.owl', ignore_cache=True)
```

#### 2. SHA256 generated from file name instead of file contents

This is a bug in the code. The way it is currently implemented, Ontobio will never look at a new file unless the file name has changed.
I am working on a fix for this where the correct approach would be to create a SHA256 from file contents. Thus, even if there is a small change to the OWL file, it would reflect in checksum. This in turn should get Ontobio to parse the OWL and create the JSON instead of re-reading the JSON stored in `/tmp`.

**Closed** 2019-03-12 02:53 UTC
