### ISSUE TITLE
switch from cachier to diskcache

### ISSUE THREAD

**Issue by cmungall** [biolink/ontobio#140] opened 2018-02-06 22:10 UTC
`diskcache` on pypi

**Comment by cmungall** [comment] 2018-05-08 14:36
also do this in https://github.com/prefixcommons/prefixcommons-py

**Comment by kshefchek** [comment] 2018-07-26 21:16
@cmungall is there some background on this (pros/cons?)

**Comment by deepakunni3** [comment] 2019-08-07 20:14
Now duplicate of #358

**Closed by deepakunni3** 2019-08-07 20:14 UTC
